//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umuly_Case
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teklif
    {
        public int ID { get; set; }
        public string Firma { get; set; }
        public string Modu { get; set; }
        public string Hareket_Sekli { get; set; }
        public string Incoterm { get; set; }
        public string Ulke { get; set; }
        public string Sehir { get; set; }
        public Nullable<int> Urun_Sayisi { get; set; }
        public string Paket_Tipi { get; set; }
        public Nullable<int> Uzunluk { get; set; }
        public string Uzunluk_Birimi { get; set; }
        public Nullable<int> Agirlik { get; set; }
        public string Agirlik_Birimi { get; set; }
        public Nullable<int> Ucret { get; set; }
        public string Para_Birimi { get; set; }
    }
}
